// Generated by gencpp from file beginner_tutorials/Active.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ACTIVE_H
#define BEGINNER_TUTORIALS_MESSAGE_ACTIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Active_
{
  typedef Active_<ContainerAllocator> Type;

  Active_()
    : direction(0)
    , speed(0.0)  {
    }
  Active_(const ContainerAllocator& _alloc)
    : direction(0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _direction_type;
  _direction_type direction;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::beginner_tutorials::Active_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Active_<ContainerAllocator> const> ConstPtr;

}; // struct Active_

typedef ::beginner_tutorials::Active_<std::allocator<void> > Active;

typedef boost::shared_ptr< ::beginner_tutorials::Active > ActivePtr;
typedef boost::shared_ptr< ::beginner_tutorials::Active const> ActiveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Active_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Active_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/ubuntu/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Active_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Active_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Active_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Active_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Active_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Active_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Active_<ContainerAllocator> >
{
  static const char* value()
  {
    return "303d95c789e3846c8cef0567c921b988";
  }

  static const char* value(const ::beginner_tutorials::Active_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x303d95c789e3846cULL;
  static const uint64_t static_value2 = 0x8cef0567c921b988ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Active_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Active";
  }

  static const char* value(const ::beginner_tutorials::Active_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Active_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 direction\n\
float32 speed\n\
";
  }

  static const char* value(const ::beginner_tutorials::Active_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Active_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Active_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Active_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Active_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<int8_t>::stream(s, indent + "  ", v.direction);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ACTIVE_H
