// Generated by gencpp from file ros_robot/Active.msg
// DO NOT EDIT!


#ifndef ROS_ROBOT_MESSAGE_ACTIVE_H
#define ROS_ROBOT_MESSAGE_ACTIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_robot
{
template <class ContainerAllocator>
struct Active_
{
  typedef Active_<ContainerAllocator> Type;

  Active_()
    : direction(0)
    , speed(0)
    , ptz(0)  {
    }
  Active_(const ContainerAllocator& _alloc)
    : direction(0)
    , speed(0)
    , ptz(0)  {
  (void)_alloc;
    }



   typedef int8_t _direction_type;
  _direction_type direction;

   typedef int8_t _speed_type;
  _speed_type speed;

   typedef int8_t _ptz_type;
  _ptz_type ptz;





  typedef boost::shared_ptr< ::ros_robot::Active_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_robot::Active_<ContainerAllocator> const> ConstPtr;

}; // struct Active_

typedef ::ros_robot::Active_<std::allocator<void> > Active;

typedef boost::shared_ptr< ::ros_robot::Active > ActivePtr;
typedef boost::shared_ptr< ::ros_robot::Active const> ActiveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_robot::Active_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_robot::Active_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ros_robot': ['/home/ubuntu/catkin_ws/src/ros_robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot::Active_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_robot::Active_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot::Active_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_robot::Active_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot::Active_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_robot::Active_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_robot::Active_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f804e429aeb8f3511a613f05f7284a12";
  }

  static const char* value(const ::ros_robot::Active_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf804e429aeb8f351ULL;
  static const uint64_t static_value2 = 0x1a613f05f7284a12ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_robot::Active_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_robot/Active";
  }

  static const char* value(const ::ros_robot::Active_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_robot::Active_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 direction\n\
int8 speed\n\
int8 ptz\n\
";
  }

  static const char* value(const ::ros_robot::Active_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_robot::Active_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.speed);
      stream.next(m.ptz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Active_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_robot::Active_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_robot::Active_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<int8_t>::stream(s, indent + "  ", v.direction);
    s << indent << "speed: ";
    Printer<int8_t>::stream(s, indent + "  ", v.speed);
    s << indent << "ptz: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ptz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ROBOT_MESSAGE_ACTIVE_H
